#!/bin/bash
while getopts ":f" opt; do #Trying to add a flag.
  case $opt in
      f)
#Using find to get all directories with .git, all git directories have that.
	find $HOME -type d -name '.git' -exec sh -c ' 
  for name; do
  dir=${name%/.git} #Removing the /.git from the results, it is kinda important.
  echo "Updating repo in directory: ${dir}"
     (git -C "$dir" pull)
  done
' _ {} +
	exit 0 #I figured that out. Haha.
	;;
      \?)
      echo "Use -f for showing directories" #In case you forget how to do that.
      exit 1
  esac
done
#Here we go again.
    find $HOME -type d -name '.git' -exec sh -c '
  for name; do
  repo=${name%/.git}
  echo Updating repo: ${repo##*/} #Only shows the repo name.
    (git "$repo" pull)
  done
' _ {} +
